### ISSUE TITLE
Great tool ! The sample curl is not working

### ISSUE THREAD

**Issue by mistertest** [saasify-sh/scrape-it#6]
Hello I used "scrape it" on 2014, I was very impressed byyour tool. I'm happy that you have building a API for your tool . 
Your Scraper is great and this idea is very cool, I want be a regular client to your service API for using scrape It in my projects like my app "CLoud Choice".
Bet when I tested the CURL Sample with 
https://reqbin.com/curl  and it's not working.
"Forbiden 403".

Thank you for your help.

**Comment by IonicaBizau** [comment]
Hi there,

saasify-sh is a third-party and I am unsure why it would not work.
The alternative is to import scrape-it locally directly in your project:
https://github.com/IonicaBizau/scrape-it

Best,
@IonicaBizau
